variables:
  DOCKER_DRIVER: overlay

stages:
  - build_and_deploy

build_and_deploy:
  tags:
    - dev
    - master
  image: docker:latest
  stage: build_and_deploy
  services:
    - name: docker:dind
  script:
    - docker-compose up --build --force-recreate --no-deps -d
  only:
    - dev
    - master
