variables:
  DOCKER_DRIVER: overlay

stages:
  - build_and_deploy

build_and_deploy:
  tags:
    - dev
    - master
  image: docker:latest
  stage: build_and_deploy
  services:
    - name: docker:dind
  before_script:
    - docker images
    - docker container ls
    - docker-compose -f docker-compose.yml down --remove-orphans -v -f || true
  script:
    - docker-compose -f docker-compose.yml up --no-start --build --force-recreate --no-deps
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag arete_ui $DOCKER_USER/arete_ui:latest
    - docker push $DOCKER_USER/arete_ui:latest
    - docker-compose -f docker-compose.yml up -d --force-recreate --no-deps
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master
