version: '3.4'

services:

  monitoring_service:
    container_name: monitoring_service
    image: automatedtestingservice/monitoring_service:latest
    restart: unless-stopped
    environment:
      BACKEND: "https://cs.ttu.ee/services/arete/api/v2/"
    ports:
      - "1080:8080"
