version: '3.4'

services:

  arete_ui:
    container_name: arete_ui
    image: arete_ui:latest
    restart: unless-stopped
    build: .
    environment:
      BACKEND: "https://cs.ttu.ee/services/arete/api/admin/"
    ports:
      - "1080:8080"
